# -*- coding: utf-8 -*-
"""Ultrarobotate.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HA-0YW3QW473ETeQA41DW968ugL_5pyA
"""

def usuario():  # define la función llamada usuario
    nombre = input("Por favor ingrese su nombre: ")  #
    print(f"Hola, {nombre}! Encantado de conocerte.")
    print()
    print(f"¿En qué te puedo ayudar, {nombre}?")

usuario()